### PR TITLE
Equalent go benchmark

### PR DESCRIPTION
**Pull request by heppu**
Fixes for #11

### CODE REVIEW

**Comment by squeaky-pl** [comment]
How, thanks for the PR. Have you managed to measure more or less what kind of speedup it makes over the previous version?

**Comment by heppu** [comment]
No, could you provide commands to reproduce your benchmarks?

**Comment by squeaky-pl** [comment]
Great. Note that I run wrk 10 times in a row with -t 1-c 100 -d 2 and pipeline.lua  script and took a median

**Comment by heppu** [comment]
Ok I ran the benchmark on the go version is 18% faster that the current go version on my machine.

**Comment by squeaky-pl** [comment]
waiting for go-fasthttp results and gonna put an errata in the article.

**Comment by heppu** [comment]
Oh sorry I forgot to set GOMAXPROCS=1. The increase was ~12% with that setup. I gotta say that that kind of takes away the advantage of Go but still is valid if you are planning to run http server on single thread instance :D

**Pull request merged**
